import jwt from 'jsonwebtoken'

// was setUser
export function generateToken(user) {

    return jwt.sign({
        _id: user._id,
        email: user.email,
        role: user.role
    }, process.env.JWT_SECRET)
}

// was getUser
export function verifyToken(token) {
    try {
        // yhan token verify hony k bad us ka payload hoga wo return hoga
        // e.g _id, email, iat (issued at time - generated by default by JWT)
        return jwt.verify(token, process.env.JWT_SECRET)
    } catch (error) {
        console.error(error);
    }
}